version = 1
SPDX-PackageName = "random-wait-action"
SPDX-PackageSupplier = "Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/AliSajid/random-wait-action"

[[annotations]]
path = "renovate.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "tsconfig.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "package.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "dist/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "lib/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".github/workflows/**.yaml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".eslintignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".markdownlintignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".prettierignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".secrets.baseline"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitleaksignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitattributes"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CODEOWNERS"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "pnpm-lock.yaml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "REUSE.toml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CODE_OF_CONDUCT.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CONTRIBUTING.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
